id: P007050
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5411
  title: མཆོག་སྤྲུལ་གསང་སྔགས་བསྟན་འཛིན་གྱི་རྣམ་ཐར་དད་གསུམ་པདྨོ་འབྱེད་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    f5330dfc22874acbbce265d780980030:
      image_group_id: I3CN5413
      title: Volume 1 of mchog sprul gsang sngags bstan 'dzin gyi rnam thar dad gsum
        pad+mo 'byed pa'i nyin byed/
      volume_number: 1
      total_pages: 192
      base_file: v001.txt
