id: P007050
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5411
  title: མཆོག་སྤྲུལ་གསང་སྔགས་བསྟན་འཛིན་གྱི་རྣམ་ཐར་དད་གསུམ་པདྨོ་འབྱེད་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    0f51e49261854abcbe40ad9cadc29dc8:
      image_group_id: I3CN5413
      title: ''
      volume_number: 1
      total_pages: 192
ebook_metadata:
  title: མཆོག་སྤྲུལ་གསང་སྔགས་བསྟན་འཛིན་གྱི་རྣམ་ཐར་དད་གསུམ་པདྨོ་འབྱེད་པའི་ཉིན་བྱེད།
  author: ''
  sku: P007050
  cover: cover.jpg
  layers:
  - pagination
